### ISSUE TITLE
Missing appcompat in build.gradle

### ISSUE THREAD

**Issue by diceroll123** [googlesamples/android-StorageProvider#1]
It's way too much work to fill out a CLA or anything like that, it's after 4 AM in the morning. My brain's not cut out for that right now.

Though this example is not what I was looking for, just gonna leave this issue here. :smiley: 

Android Studio won't build newest build because it uses AppCompat, try adding `compile "com.android.support:appcompat-v7:23.0.0"`to the dependencies in the `Application` `build.gradle`. :+1: 

You may have this issue elsewhere that auto-updates builds like this.

Made an issue here because the link under Support is broken. 

> If you've found an error in this sample, please file an issue: https://github.com/googlesamples/android-MyCloud

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
