### ISSUE TITLE
missing StorageProviderFragment

### ISSUE THREAD

**Issue by gerardgilliland** [googlesamples/android-StorageProvider#2]
Android Studio
Android Studio Projects Quick Start
Import an Android code sample
Storage Provider
https://github.com/googlesamples/android-StorageProvider/
error in Main line 48: StorageProviderFragment fragment = new StorageProviderFragment();
Caused by missing StorageProviderFragment
Thank you.
Gerard

**Comment by kaamel** [comment]
I managed to run the sample code by changing the StorageProviderFragment to MyCloudFragment in the MainActivity.

Kaamel

**Comment by gerardgilliland** [comment]
Kaamel,

Thank you.

That works.

I am glad you could see past the code for a solution.

Gerard

**Comment by keyboardsurfer** [comment]
(Internal: 25638573)

**Comment by keyboardsurfer** [comment]
Fixed with latest push.

**Comment by gerardgilliland** [comment]
Ben,

Thank you.

Gerard
