### ISSUE TITLE
sample files are not copied when instant run feature is used from Android Studio

### ISSUE THREAD

**Issue by kyunghoj** [googlesamples/android-StorageProvider#3]
`writeDummyFilesToStorage()` checks `mBaseDir` directory for an existing sub-directory to see if sample files have been already copied. But with a newer Android Studio, if instant-run is enabled, there is actually a directory named `instant-run/`, so this code does not copy sample image files.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
