### ISSUE TITLE
Cancellation Signal is always null?

### ISSUE THREAD

**Issue by anmolvermamm** [googlesamples/android-StorageProvider#6]
https://github.com/googlesamples/android-StorageProvider/blob/6f21c5616efed8058b9759202ae1c09d2f124821/Application/src/main/java/com/example/android/storageprovider/MyCloudProvider.java#L296

I have an implementation of document provider, why is it that the cancellation signal is always null, when someone tries to opendocument from documentprovider ?

Thanks for your time!

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above. Thank you!
